/*
 * Go_Testing API
 *
 * Openapi specification for the cmd/web main
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gin

// Count - Count of the pods in the namespace
type Count struct {

	Count int32 `json:"count"`
}
