apiVersion: batch/v1
kind: Job
metadata:
  name: '{{ .Values.name }}'
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        app: '{{ .Values.name }}'
    spec:
      restartPolicy: "Never"
      serviceAccountName: '{{ .Values.name }}'
      containers:
        - name: '{{ .Values.name }}'
          image: '{{ .Values.image }}:latest'
          imagePullPolicy: Never
          resources:
            limits:
              memory: '1000Mi'
            requests:
              cpu: '1000m'
              memory: '1000Mi'


